# Generated by Django 5.1.6 on 2025-07-22 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vethospital',
            options={'ordering': ['-rating', 'distance_km'], 'verbose_name': '동물병원', 'verbose_name_plural': '동물병원 목록'},
        ),
        migrations.AddField(
            model_name='vethospital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vethospital',
            name='description',
            field=models.TextField(blank=True, verbose_name='병원 설명'),
        ),
        migrations.AddField(
            model_name='vethospital',
            name='distance_km',
            field=models.FloatField(default=0.0, verbose_name='거리(km)'),
        ),
        migrations.AddField(
            model_name='vethospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/', verbose_name='병원 이미지'),
        ),
        migrations.AddField(
            model_name='vethospital',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='응급실 운영'),
        ),
        migrations.AddField(
            model_name='vethospital',
            name='operating_hours',
            field=models.CharField(default='09:00 - 18:00', max_length=100, verbose_name='운영시간'),
        ),
        migrations.AddField(
            model_name='vethospital',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='별점'),
        ),
        migrations.AddField(
            model_name='vethospital',
            name='specialties',
            field=models.TextField(blank=True, verbose_name='전문분야 (쉼표로 구분)'),
        ),
        migrations.AddField(
            model_name='vethospital',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='vethospital',
            name='address',
            field=models.CharField(max_length=200, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='vethospital',
            name='is_24hours',
            field=models.BooleanField(default=False, verbose_name='24시간 운영'),
        ),
        migrations.AlterField(
            model_name='vethospital',
            name='latitude',
            field=models.FloatField(verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='vethospital',
            name='longitude',
            field=models.FloatField(verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='vethospital',
            name='name',
            field=models.CharField(max_length=100, verbose_name='병원명'),
        ),
        migrations.AlterField(
            model_name='vethospital',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
    ]
