# Generated by Django 5.2.4 on 2025-07-28 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_app', '0002_alter_vethospital_options_vethospital_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='즐겨찾기 추가일')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency_app.vethospital', verbose_name='병원')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '병원 즐겨찾기',
                'verbose_name_plural': '병원 즐겨찾기 목록',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'hospital')},
            },
        ),
    ]
