# Generated by Django 5.2 on 2025-04-25 16:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='보험사명')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='신뢰도 등급')),
                ('customer_satisfaction', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='고객 만족도')),
                ('contact_number', models.CharField(max_length=20, verbose_name='연락처')),
                ('website', models.URLField(verbose_name='홈페이지')),
                ('description', models.TextField(verbose_name='회사 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '보험사',
                'verbose_name_plural': '보험사들',
            },
        ),
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='기본 보험료')),
                ('min_age', models.PositiveIntegerField(verbose_name='최소 나이')),
                ('max_age', models.PositiveIntegerField(verbose_name='최대 나이')),
                ('coverage_period', models.PositiveIntegerField(verbose_name='보장 기간')),
                ('renewal_cycle', models.PositiveIntegerField(verbose_name='갱신 주기')),
                ('coverage_details', models.JSONField(verbose_name='보장 내역')),
                ('coverage_limits', models.JSONField(verbose_name='보장 한도')),
                ('special_benefits', models.JSONField(verbose_name='특별 혜택')),
                ('sure_index', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='안전도 지수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insurancecompany', verbose_name='보험사')),
            ],
            options={
                'verbose_name': '보험상품',
                'verbose_name_plural': '보험상품들',
            },
        ),
        migrations.CreateModel(
            name='InsuranceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', '강아지'), ('cat', '고양이')], max_length=10)),
                ('pet_age', models.PositiveIntegerField()),
                ('inquiry_type', models.CharField(choices=[('price', '보험료 문의'), ('coverage', '보장 내용 문의'), ('claim', '보험금 청구 문의'), ('other', '기타 문의')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('answer', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuranceproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='평점')),
                ('comment', models.TextField(verbose_name='리뷰내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuranceproduct', verbose_name='보험상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '보험리뷰',
                'verbose_name_plural': '보험리뷰들',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
