# Generated by Django 5.2 on 2025-04-25 16:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='insurance/company_logos/'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insurancereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='회사 설명'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='rating',
            field=models.FloatField(default=3.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='신뢰도 등급'),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='홈페이지'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='insurance_app.insurancecompany', verbose_name='보험사'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='sure_index',
            field=models.FloatField(default=0.0, verbose_name='안전도 지수'),
        ),
        migrations.AlterField(
            model_name='insurancereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='평점'),
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('dog', '개'), ('cat', '고양이')], max_length=10)),
                ('breed', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('weight', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', '수컷'), ('female', '암컷')], max_length=10)),
                ('is_neutered', models.BooleanField(default=False)),
                ('medical_history', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_premium', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuranceproduct')),
                ('pet_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_choices', to='insurance_app.petprofile')),
            ],
        ),
    ]
