# Generated by Django 5.2 on 2025-04-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_insurancecompany_logo_insuranceproduct_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='max_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='최대 체중'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='min_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='최소 체중'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='pet_type',
            field=models.CharField(choices=[('dog', '강아지'), ('cat', '고양이')], default='cat', max_length=10, verbose_name='동물 종류'),
        ),
    ]
