# Generated by Django 5.2 on 2025-04-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_insuranceproduct_max_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True)),
                ('cause', models.TextField(blank=True)),
                ('tip', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.IntegerField()),
                ('wild', models.BooleanField(default=False)),
                ('disease', models.ManyToManyField(blank=True, to='insurance_app.disease')),
            ],
        ),
    ]
