# Generated by Django 5.2 on 2025-04-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0004_disease_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cover_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
