# Generated by Django 5.2 on 2025-04-28 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0005_disease_cover_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecompany',
            name='customer_satisfaction',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='고객 만족도'),
        ),
    ]
