# Generated by Django 5.2 on 2025-04-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_alter_insurancecompany_customer_satisfaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_type', models.IntegerField()),
                ('price', models.IntegerField()),
                ('wild', models.BooleanField(default=False)),
                ('detail', models.TextField()),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuranceproduct')),
            ],
        ),
    ]
