# Generated by Django 5.2 on 2025-04-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0007_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('basic', models.JSONField()),
                ('special', models.JSONField(blank=True, null=True)),
                ('all_cover', models.JSONField()),
                ('content', models.TextField(blank=True)),
                ('price_score', models.FloatField()),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuranceproduct')),
            ],
        ),
    ]
