# Generated by Django 5.2 on 2025-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0008_insurancedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.IntegerField()),
                ('animal_name', models.CharField(max_length=100)),
                ('species', models.IntegerField()),
                ('animal_birth', models.IntegerField()),
                ('hospitalization', models.IntegerField()),
                ('outpatient', models.IntegerField()),
                ('skin_disease', models.IntegerField()),
                ('operation', models.IntegerField()),
                ('patella', models.IntegerField()),
                ('dental', models.IntegerField()),
                ('urinary', models.IntegerField()),
                ('liability', models.IntegerField()),
                ('insurance_choice', models.IntegerField()),
            ],
        ),
    ]
