# Generated by Django 5.2 on 2025-04-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0010_covertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('content', models.TextField()),
                ('item_url', models.URLField()),
                ('image', models.URLField()),
                ('cover_type', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='CoverType',
        ),
    ]
