# Generated by Django 5.2 on 2025-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0011_items_delete_covertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='보험사명'),
        ),
    ]
