# Generated by Django 5.2 on 2025-04-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0012_covertype_insuranceproduct_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='insurance_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='보험상품명'),
        ),
    ]
