# Generated by Django 5.2 on 2025-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0013_insuranceproduct_insurance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='species',
            field=models.IntegerField(blank=True, null=True, verbose_name='동물 종'),
        ),
    ]
