# Generated by Django 5.2 on 2025-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0014_insuranceproduct_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='company_score',
            field=models.FloatField(blank=True, null=True, verbose_name='보험사 평점'),
        ),
    ]
