# Generated by Django 5.2 on 2025-04-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0015_insuranceproduct_company_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='company_url',
            field=models.URLField(blank=True, null=True, verbose_name='보험사 URL'),
        ),
    ]
