# Generated by Django 5.2 on 2025-04-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0016_insuranceproduct_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='insurance/company_logos/', verbose_name='보험사 로고'),
        ),
    ]
