# Generated by Django 5.2 on 2025-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0017_insuranceproduct_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='renewal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='갱신 정보'),
        ),
    ]
