# Generated by Django 5.2 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0018_insuranceproduct_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='payment_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='납입 기간'),
        ),
    ]
