# Generated by Django 5.2 on 2025-04-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0019_insuranceproduct_payment_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='상품 설명'),
        ),
    ]
