# Generated by Django 5.2 on 2025-04-20 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_app', '0002_pet_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('nail', '발톱깎기'), ('ear', '귀청소'), ('fur', '털정리'), ('brush', '양치하기')], max_length=20)),
                ('last_date', models.DateField()),
                ('interval', models.PositiveIntegerField(help_text='주기 간격 숫자')),
                ('unit', models.CharField(choices=[('day', '일'), ('week', '주'), ('month', '월')], max_length=10)),
                ('next_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_schedule_events', to='common_app.pet')),
            ],
            options={
                'ordering': ['next_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('start_time', models.DateField(verbose_name='시작 날짜')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='종료 날짜')),
                ('category', models.CharField(choices=[('nail', '발톱깎기'), ('ear', '귀청소'), ('brush', '양치하기'), ('fur', '털정리')], max_length=20, verbose_name='카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='common_app.pet', verbose_name='고양이')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '일정',
                'verbose_name_plural': '일정들',
                'ordering': ['-start_time'],
            },
        ),
    ]
