# Generated by Django 5.2 on 2025-04-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_board_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_together',
            field=models.BooleanField(default=False, verbose_name='함께 작성'),
        ),
    ]
