# Generated by Django 5.2 on 2025-04-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_board_app', '0002_post_is_together'),
        ('common_app', '0005_pet_gender_pet_neutered_pet_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pets',
            field=models.ManyToManyField(blank=True, related_name='together_posts', to='common_app.pet', verbose_name='함께한 반려동물들'),
        ),
    ]
