# Generated by Django 5.2 on 2025-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_board_app', '0003_post_pets'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_etc',
            field=models.BooleanField(default=False, verbose_name='기타 작성'),
        ),
    ]
