# Generated by Django 5.2 on 2025-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hospital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
