# Generated by Django 5.2.4 on 2025-07-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_event_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
