# Generated by Django 5.2.4 on 2025-07-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_event_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_reservation',
            field=models.BooleanField(default=False, help_text='예약 여부'),
        ),
    ]
