# Generated by Django 5.2 on 2025-04-26 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0004_pet_weight'),
        ('weight_tracker_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weight',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='common_app.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('user', 'pet', 'date')},
        ),
    ]
