# Generated by Django 5.2 on 2025-04-21 15:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_app', '0002_pet_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='메모')),
                ('type', models.CharField(choices=[('feed', '사료'), ('snack', '간식')], default='feed', max_length=10, verbose_name='타입')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('purchase_link', models.URLField(blank=True, verbose_name='구매처 링크')),
                ('rating', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='만족도')),
                ('previous_food', models.CharField(blank=True, max_length=200, verbose_name='이전 사료')),
                ('quantity_kg', models.FloatField(default=0, verbose_name='구매량(kg)')),
                ('duration_days', models.PositiveIntegerField(default=0, verbose_name='소비 기간(일)')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.pet', verbose_name='반려동물')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '식사 기록',
                'verbose_name_plural': '식사 기록',
                'ordering': ['-start_time'],
            },
        ),
    ]
