# Generated by Django 5.2 on 2025-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodevent',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
