# Generated by Django 5.2 on 2025-04-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calendar', '0002_foodevent_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodevent',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='가격'),
        ),
    ]
