# Generated by Django 5.2 on 2025-04-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_calendar', '0004_otherpurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherPurchase',
        ),
    ]
