# Generated by Django 5.2.4 on 2025-07-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calendar', '0005_delete_otherpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodevent',
            name='purchase_link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='구매처 링크'),
        ),
    ]
