# Generated by Django 5.2.4 on 2025-07-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_calendar', '0006_alter_foodevent_purchase_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodevent',
            name='price',
            field=models.FloatField(default=0, verbose_name='가격'),
        ),
    ]
