# Generated by Django 5.2 on 2025-04-19 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('breed', models.CharField(choices=[('persian', '페르시안'), ('siamese', '샴'), ('maine_coon', '메인쿤'), ('ragdoll', '랙돌'), ('british', '브리티시 숏헤어'), ('scottish', '스코티시 폴드'), ('russian', '러시안 블루'), ('abyssinian', '아비시니안'), ('bengal', '벵갈'), ('sphynx', '스핑크스'), ('etc', '기타')], max_length=20, verbose_name='종')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
