# Generated by Django 5.2 on 2025-04-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0002_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(choices=[('dog', '강아지'), ('cat', '고양이')], default='cat', max_length=10, verbose_name='종류'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=20, verbose_name='품종'),
        ),
    ]
