# Generated by Django 5.2 on 2025-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0003_pet_pet_type_alter_pet_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='체중(kg)'),
        ),
    ]
