# Generated by Django 5.2 on 2025-04-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0004_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('male', '수컷'), ('female', '암컷')], default='male', max_length=10, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='pet',
            name='neutered',
            field=models.BooleanField(default=False, verbose_name='중성화 여부'),
        ),
        migrations.AddField(
            model_name='pet',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='특이사항'),
        ),
    ]
