# Generated by Django 5.1.6 on 2025-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0005_pet_gender_pet_neutered_pet_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='preference_dict',
            field=models.JSONField(blank=True, default=dict, verbose_name='보험 선호도'),
        ),
        # notes 필드의 NULL 값을 빈 문자열로 먼저 변경
        migrations.RunSQL(
            "UPDATE common_app_pet SET notes = '' WHERE notes IS NULL",
            reverse_sql="UPDATE common_app_pet SET notes = NULL WHERE notes = ''"
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, verbose_name='특이사항'),
        ),
    ]
