# Generated by Django 5.2.4 on 2025-07-23 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_app', '0006_auto_20250723_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name'], 'verbose_name': '반려동물', 'verbose_name_plural': '반려동물들'},
        ),
    ]
