# Generated by Django 5.2 on 2025-04-30 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_communitypost_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_community_comments', to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
    ]
