# Generated by Django 5.2 on 2025-04-23 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_app', '0002_pet_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='구매일')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('type', models.CharField(max_length=50, verbose_name='타입')),
                ('product_name', models.CharField(max_length=100, verbose_name='상품명')),
                ('purchase_link', models.URLField(blank=True, verbose_name='구매처 링크')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='만족도')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_app.pet', verbose_name='반려동물')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '기타 구매',
                'verbose_name_plural': '기타 구매',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
